stages:
  - Build

Cross-Cloud:
  image: crosscloudci/debian-docker 
  stage: Build
  script:
    - git clone https://github.com/crosscloudci/cross-cloud.git -b "$CI_COMMIT_REF_SLUG" && cd ./cross-cloud
    - docker login "$CI_REGISTRY" -u "$DOCKER_USER" -p "$DOCKER_TOKEN"
    - docker build --pull -t "$CI_REGISTRY/cncf/cross-cloud/provisioning:$CI_COMMIT_REF_SLUG" .
    - sleep 10000000
    - docker push "$CI_REGISTRY/cncf/cross-cloud/provisioning:$CI_COMMIT_REF_SLUG"

Socat:
  stage: Build
  image: crosscloudci/debian-docker
  script:
    - git clone https://github.com/crosscloudci/cross-cloud.git -b "$CI_COMMIT_REF_SLUG" && cd ./cross-cloud
    - docker login "$CI_REGISTRY" -u "$DOCKER_USER" -p "$DOCKER_TOKEN"
    - docker build --pull -t "$CI_REGISTRY/cncf/cross-cloud/socat:$CI_COMMIT_REF_SLUG" ./socat/
    - docker push "$CI_REGISTRY/cncf/cross-cloud/socat:$CI_COMMIT_REF_SLUG"
